### PR TITLE
ImageGroupCompiler, Matrix and Vector3 changes

### PR DESCRIPTION
**Pull request by Uniphix**
Hey all, I added some good properties within Matrix.cs that can help our game development which is right now being used as an extensions to set/get these values.  As for the Vector3 constants they are quick shortcuts to do things like Vector3.Up rather than having to do new Vector3( 0, 1, 0 )

### CODE REVIEW

**Comment by Discosultan** [comment]
I think these are a great addition!

One suggestion, though: Paradox Math API currently supports operations both for left-handed and right-handed coordinate systems. Instead of simply adding Vector3.Forward or Vector3.Backward, I'd implement them as Vector3.ForwardRH, Vector3.ForwardLH and the same with Backward. Similarily to [how it's implemented in SharpDX Math API](https://github.com/sharpdx/SharpDX/blob/d0376184b166859c1fcc9dcbfb58cd780068d8b2/Source/SharpDX.Mathematics/Vector3.cs#L109-L127).

**Comment by Uniphix** [comment]
You know what your right I agree, I've added the suggested modifications

**Comment by Uniphix** [comment]
Funny thing Alex that was what I was thinking but I wasn't sure how exactly you guys planned on doing it

**Comment by Discosultan** [comment]
Right, it does make perfect sense to follow a convention instead.

I think the reason providing both LH and RH jumped to my head and why I wanted to put it out here was because [Matrix struct at the moment provides both LH and RH factory methods for view and projection matrices](https://github.com/SiliconStudio/paradox/blob/master/sources/common/core/SiliconStudio.Core.Mathematics/Matrix.cs#L1875-L2299). This probably painted a wrong illusion to me.

Anyway, yes, I agree with you guys and SORRY for creating confusion!

**Comment by Uniphix** [comment]
I agree with @Discosultan in Matrix having both RH/LH got me confusing too.  If you plan on just making them straight RH then removing RH/LH prefix and having one RH function will help a lot especially in our development planning.

Upx

**Comment by Uniphix** [comment]
Hello, for some reason I think that ImageGroupCompiler was accidental made internal, when all the other classes below are public, it really makes it difficult to use it.

**Comment by xen2** [comment]
Even if we make ImageGroupCompiler public, we can't guarantee that it will be stable in terms of API.

**Pull request closed without merging**
